language: python
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - gfortran
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script: python -m pytest
notifications:
  email: false
